#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-modello
Version  : 1.8.3
Release  : 2
URL      : http://repo2.maven.org/maven2/org/codehaus/modello/modello/1.8.3/modello-1.8.3-source-release.zip
Source0  : http://repo2.maven.org/maven2/org/codehaus/modello/modello/1.8.3/modello-1.8.3-source-release.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: jdk-modello-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-atinject
BuildRequires : jdk-base64coder
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-beanutils
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-file-management
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-hamcrest
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jackson-annotations
BuildRequires : jdk-jackson-core
BuildRequires : jdk-jackson-databind
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-jtidy
BuildRequires : jdk-junit4
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-dependency-analyzer
BuildRequires : jdk-maven-dependency-plugin
BuildRequires : jdk-maven-dependency-tree
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-io
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-qdox
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snakeyaml
BuildRequires : jdk-snappy-java
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
Modello
=======================
Modello is a framework for code generation from a simple model.

%package data
Summary: data components for the jdk-modello package.
Group: Data

%description data
data components for the jdk-modello package.


%prep
%setup -q -n modello-1.8.3

python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :maven-site-plugin
sed -i s/maven-project/maven-core/ modello-maven-plugin/pom.xml

%build
python3 /usr/share/java-utils/mvn_build.py -f -- -Dmaven.version=3.1.1

%install
xmvn-install  -R .xmvn-reactor -n modello -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/modello/modello-core.jar
/usr/share/java/modello/modello-maven-plugin.jar
/usr/share/java/modello/modello-plugin-converters.jar
/usr/share/java/modello/modello-plugin-dom4j.jar
/usr/share/java/modello/modello-plugin-jackson.jar
/usr/share/java/modello/modello-plugin-java.jar
/usr/share/java/modello/modello-plugin-jdom.jar
/usr/share/java/modello/modello-plugin-jsonschema.jar
/usr/share/java/modello/modello-plugin-sax.jar
/usr/share/java/modello/modello-plugin-snakeyaml.jar
/usr/share/java/modello/modello-plugin-stax.jar
/usr/share/java/modello/modello-plugin-xdoc.jar
/usr/share/java/modello/modello-plugin-xml.jar
/usr/share/java/modello/modello-plugin-xpp3.jar
/usr/share/java/modello/modello-plugin-xsd.jar
/usr/share/java/modello/modello-test.jar
/usr/share/maven-metadata/modello.xml
/usr/share/maven-poms/modello/modello-core.pom
/usr/share/maven-poms/modello/modello-maven-plugin.pom
/usr/share/maven-poms/modello/modello-plugin-converters.pom
/usr/share/maven-poms/modello/modello-plugin-dom4j.pom
/usr/share/maven-poms/modello/modello-plugin-jackson.pom
/usr/share/maven-poms/modello/modello-plugin-java.pom
/usr/share/maven-poms/modello/modello-plugin-jdom.pom
/usr/share/maven-poms/modello/modello-plugin-jsonschema.pom
/usr/share/maven-poms/modello/modello-plugin-sax.pom
/usr/share/maven-poms/modello/modello-plugin-snakeyaml.pom
/usr/share/maven-poms/modello/modello-plugin-stax.pom
/usr/share/maven-poms/modello/modello-plugin-xdoc.pom
/usr/share/maven-poms/modello/modello-plugin-xml.pom
/usr/share/maven-poms/modello/modello-plugin-xpp3.pom
/usr/share/maven-poms/modello/modello-plugin-xsd.pom
/usr/share/maven-poms/modello/modello-plugins.pom
/usr/share/maven-poms/modello/modello-test.pom
/usr/share/maven-poms/modello/modello.pom
